### PR TITLE
464: TMB warnings

### LINKED ISSUE #464: add warnings for 2 (old) TMB problems (TMB version, TMB option)
cf. #462 

To do:

- [x] TMB option
- [x] TMB version

### PR DESCRIPTION
**Pull request by danielinteractive**
closes #464

### CODE REVIEW

**Comment by danielinteractive** [comment]
@clarkliming this would be ready for review now since `TMB` has been updated on CRAN

**Comment by danielinteractive** [comment]
@cicdguy Hi Dinakar, quick question, how would we get the latest CRAN version of the package `TMB` installed here during the check? Just wait a bit or do we need to trigger that somehow?

**Comment by danielinteractive** [comment]
That would be great, thanks @cicdguy !

**Review by clarkliming — APPROVED** [review]
looks good to me

**Pull request merged**
