### PR TITLE
ignore windows binaries

### PR DESCRIPTION
**Pull request by kkmann**
# Description

well, ignore windows bianries (.dll) : )

see #98

### CODE REVIEW

**Comment by kkmann** [comment]
@danielinteractive is there a specific reason *.o *.so *.dll  should only be ignored in subfolders? could also just globally ignore binaries to be on the safe side.

**Comment by danielinteractive** [comment]
@kkmann no specific reason, feel free to change the object file ignore rule

**Review by danielinteractive — APPROVED** [review]
first PR for @kkmann ! :-) thank you

**Comment by kkmann** [comment]
yeah... x)

**Comment by kkmann** [comment]
@danielinteractive looks like a connection fail, can you rerun the checks and merge?

**Pull request merged**
